site_name: Testcontainers for NodeJS
site_url: https://node.testcontainers.org
repo_name: 'testcontainers-node'
repo_url: 'https://github.com/testcontainers/testcontainers-node'
edit_uri: edit/main/docs/

theme:
  name: 'material'
  custom_dir: 'docs/site/theme'
  palette:
    scheme: testcontainers
  font:
    text: Roboto
    code: Roboto Mono
  logo: 'site/logo.svg'
  favicon: 'site/favicon.ico'

extra_css:
  - 'site/css/extra.css'
  - 'site/css/tc-header.css'

plugins:
  - search
  - codeinclude
  - markdownextradata

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Supported container runtimes: supported-container-runtimes.md
  - Features:
      - Containers: features/containers.md
      - Images: features/images.md
      - Networking: features/networking.md
      - Compose: features/compose.md
      - Wait strategies: features/wait-strategies.md
      - Advanced: features/advanced.md
  - Modules:
      - ArangoDB: modules/arangodb.md
      - Cassandra: modules/cassandra.md
      - ChromaDB: modules/chromadb.md
      - Couchbase: modules/couchbase.md
      - Elasticsearch: modules/elasticsearch.md
      - GCloud: modules/gcloud.md
      - HiveMQ: modules/hivemq.md
      - Kafka: modules/kafka.md
      - Localstack: modules/localstack.md
      - MariaDB: modules/mariadb.md
      - MongoDB: modules/mongodb.md
      - MSSQLServer: modules/mssqlserver.md
      - MySQL: modules/mysql.md
      - Nats: modules/nats.md
      - Neo4J: modules/neo4j.md
      - Ollama: modules/ollama.md
      - PostgreSQL: modules/postgresql.md
      - Qdrant: modules/qdrant.md
      - RabbitMQ: modules/rabbitmq.md
      - Redis: modules/redis.md
      - Redpanda: modules/redpanda.md
      - Selenium: modules/selenium.md
      - Weaviate: modules/weaviate.md
  - Configuration: configuration.md
