# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ${{matrix.os-version}}

    strategy:
      matrix:
        os-version: [ubuntu-latest]
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Test ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
      
  dind:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        node-image-version: [10-alpine, 12-alpine, 14-alpine]

    steps:
    - uses: actions/checkout@v2
    - name: Test DIND ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: docker run -i --rm -v /var/run/docker.sock:/var/run/docker.sock -v "$HOME:$HOME" -v "$PWD:$PWD" -w "$PWD" node:${{ matrix.node-image-version }} npm ci && npm test
